### ISSUE TITLE
Any plan for making python 3 version?

### ISSUE THREAD

**Issue by Latif0516** [yuhonglin/YTCrawl#4]
Hello! Thank you so much for sharing your code.

I am a python3 user and try to convert your code to python3 version but there are still some errors occurred. Do you have any plan to make a python3 version? Thank you!

**Comment by abeburnett** [comment]
+1

**Comment by yuhonglin** [comment]
Hi @Latif0516 and @abeburnett, thanks for the proposal! But I am not very experienced with python3. And this piece of code was actually written in a hurry, now I can see many flaws. I am quite busy with my work these days. So if possible I warmly welcome any contributions!
