### ISSUE TITLE
Quota exceeded

### ISSUE THREAD

**Issue by ayush1997** [yuhonglin/YTCrawl#6]
Hi
I have around 3,00,000 video ids.The scraper gives "Quota exceeded" error after approx 50 requests.
What's the workaround as I need to crawl a huge no. of video ids.I am using "Single Crawl" right now.
Thanks!

**Comment by yuhonglin** [comment]
Hi,
I guess this is because you have requested too frequently. Try to add some time delay between each call of  "single crawl" or try to use the "batch crawl" which will limit the speed automatically.
