### ISSUE TITLE
Exception: meet error when update the cookies

### ISSUE THREAD

**Issue by NevenaR** [yuhonglin/YTCrawl#7]
I am trying to get statistics for a single video but for any video i get this:

ExceptionTraceback (most recent call last)
<ipython-input-11-1d3aaac641a8> in <module>()
      2 youtube_link="https://www.youtube.com/watch?v=lWA2pjMjpBs"
      3 c = Crawler()
----> 4 c.single_crawl(youtube_link.split('v=')[1])

/Users/nr/YTCrawl-master/crawler.pyc in single_crawl(self, key)
    346         """
    347         if self._last_cookie_update_time == None:
--> 348             self.update_cookie_and_sectiontoken()
    349 
    350 

/Users/nr/YTCrawl-master/crawler.pyc in update_cookie_and_sectiontoken(self)
    146         self._cookie_update_on = True
    147 
--> 148         self.period_update()
    149 
    150 

/Users/nr/YTCrawl-master/crawler.pyc in period_update(self)
    195                     self._mutex_crawl.release()
    196                     self.email('meet error when update the cookies, please set a new seed video (%s)' % str(e))
--> 197                     raise Exception('meet error when update the cookies, please set a new seed video (%s)' % str(e))
    198 
    199             state = 'success'

Exception: meet error when update the cookies, please set a new seed video (statistics disabled)

Is there a way to get over this?

**Comment by NevenaR** [comment]
Just adding c.set_seed_videoID(id) to fixes it

**Comment by ghost** [comment]
@NevenaR 
Hi NevenaR, 
I am having the same issue here, can you explain more how you fixed it?

**Comment by NevenaR** [comment]
@MohammedSabbah 
Hello,
For me setting the seed before starting the crawling solved the problem.
So this should work: 
 ```python
  c = Crawler()
  c.set_seed_videoID(video_id)
  c.single_crawl(video_id)
```
